# Generated by Django 4.0.4 on 2022-05-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_tests', '0002_alter_test_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
