# Generated by Django 4.0.4 on 2022-05-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_report', models.FileField(blank=True, null=True, upload_to='reports_PDF')),
                ('send_message', models.CharField(blank=True, max_length=250, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('approved_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicine_tests.testorder')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
